### PR TITLE
Add support for /etc/master.passwd

### PR DESCRIPTION
**Pull request by bodgit**
Found on OpenBSD and possibly other BSD's.

Also update /etc/group lens with support for NIS map with an overridden and
disabled password, i.e. `+:*::`

### CODE REVIEW

**Comment by raphink** [comment]
LGTM.

**Comment by raphink** [comment]
Just one thing. I'd rather see the changes in `Group` in a separate commit from the one creating the new lens.

**Comment by bodgit** [comment]
Fixed

**Comment by raphink** [comment]
Merged as fd9cf8c..51d4879

**Pull request closed without merging**
