### PR TITLE
Opendkim: new lens for /etc/opendkim.conf

### PR DESCRIPTION
**Pull request by craigmiskell**
New lens for Opendkim, specifically /etc/opendkim.conf

### CODE REVIEW

**Comment by lutter** [comment]
thanks for the contribution ! Unfortunately, when I run this through augparse with `augparse lenses/opendkim.aug` I get the following error:
```
Syntax error in lens definition
lenses/opendkim.aug:16.21-.75:Invalid regular expression: Unmatched ( or \(
lenses/opendkim.aug:35.22-.63:Invalid regular expression: Unmatched ( or \(
lenses/opendkim.aug:41.22-.64:Invalid regular expression: Unmatched ( or \(
lenses/opendkim.aug:52.16-.25:Undefined variable integerkv
lenses/opendkim.aug:54.31-.36:Undefined variable entry
lenses/opendkim.aug:56.22-.25:Undefined variable lns
```

The problem seems to be that you split regular expressions across lines like so: `key /(a|b/ . /c|d)/`. That doesn't work since everything between a pair of `/.../` needs to be a valid regular expression. Since the entire expression is just a union, the parentheses are actually unnecessary and you should write `/a|b/ | /c|d/` instead.

**Comment by lutter** [comment]
I actually made the changes I suggested and commited this now as 8eb61f2f

Thanks again for the contribution !

**Comment by craigmiskell** [comment]
Ahh, thank you.  I saw the failure, but couldn't figure it out and haven't had the time to debug in depth.  Thanks for fixing it.

**Comment by lutter** [comment]
Would have been easier if some chump hadn't given you bad advice on the first PR ;)

**Pull request closed without merging**
