### PR TITLE
fix restrict to allow also -4 and also fix save/store ability

### PR DESCRIPTION
**Pull request by jreidinger**
Restrict now can also have -4, so ipv6 no longer have sense alone, so changed to "ip" key with value "4" or "6". Also tests are adapted to new behavior

### CODE REVIEW

**Comment by raphink** [comment]
OK.

Just a few thoughts:

* Could you add a test for "ipv4", too?
* This is a breaking change. Another option would be to keep the `ipv6` node and add an `ipv4` node option. @lutter, @domcleal any thoughts on that?

**Comment by jreidinger** [comment]
@raphink yep, I will add it

**Comment by domcleal** [comment]
> This is a breaking change. Another option would be to keep the ipv6 node and add an ipv4 node option

That sounds like a better idea to me, treat it as a flag rather than node with a `4` or `6` value.

**Comment by jreidinger** [comment]
test added
btw there is also one another missing option. Restrict can have also optional mask after address ( but only if default is not used ), so maybe it make more sense to have it all as nodes like
```
restrict => {
  "address" => "5.5.5.5",
  "mask" => "255.255.0.0",
  "ip" => "4",
  "action[1]" => ...
}
```
but we do not use mask too much, so just side note.

**Comment by jreidinger** [comment]
> That sounds like a better idea to me, treat it as a flag rather than node with a 4 or 6 value.

if there is agreement on it, I can change it.

**Comment by raphink** [comment]
Yes, I'd rather go with the other option, for the sake of compatibility.

**Comment by jreidinger** [comment]
updated to be backward compatible as agreed.

**Comment by jreidinger** [comment]
thanks

**Comment by raphink** [comment]
no, thank you :smile:

**Pull request merged**
