### PR TITLE
openvpn: added all options available in OpenVPN2.3 and all tests

### PR DESCRIPTION
**Pull request by dafugg**
I've added all possible options in OpenVPN 2.3 from the man page at https://community.openvpn.net/openvpn/wiki/Openvpn23ManPage and tests for lots (all?) permutations of those options.

### CODE REVIEW

**Comment by dafugg** [comment]
I should mention.. the IPv6 options are poorly documented. I've done my best to guess what they should look like but I haven't been able to test them here.

I also didn't add any of the windows-specific options.

**Comment by dafugg** [comment]
I manually ran augparse as the gnulib tests weren't working on my system (test-lock and test-thread_create fail in gnulib). I've run just the augeas lense tests and openvpn passes here:
PASS: lens-openvpn.sh
however the check takes quite a while. Could someone else confirm that the test passes?

**Comment by raphink** [comment]
```
$ \time -v augparse -I lenses/ lenses/openvpn.aug

	Maximum resident set size (kbytes): 4266356
```

is the problem

Just switching to `Rx.ip` instead of `Rx.ipv4` already eats up almost 2GB, because of the complexity of `Rx.ipv6`. I think it would be reasonable to make this lens a bit less strict on values, to save a bit of memory on typechecking it.

**Comment by raphink** [comment]
Replacing all occurrences of `Rx.ipv6` with `Rx.word` already gets the max resident size down to 2062396.

Maybe it would be good to have a local, loose lens for IPv6 (something like `/[0-9A-Fa-f:]+/` or so) that would already save 2GB.

**Comment by dafugg** [comment]
Thanks for the update @raphink . I have built augeas here in a Yocto 'ptest' image to run in a VM with a hard 1.5GB limit. All of the tests passed consistently in this environment.

**Comment by raphink** [comment]
LGTM, I'll merge.

**Pull request merged**
