### PR TITLE
Add Github workflow to create releases with complete source tarballs

### LINKED ISSUE #741: any plans to ship complete source tarballs?
http://download.augeas.net/ contains source tarballs of older releases. Since the gnulib bits are missing form the auto-generated source tarball attached to the 1.13.0 Github release, the documented `./configure && make && sudo make install` trifecta no longer works

Are you still planning to provide complete tarballs?

### PR DESCRIPTION
**Pull request by hillu**
To see how this works, see the [Releases](https://github.com/hillu/augeas/releases) in my fork where a release attached to the `v42` tag should appear soon.

This should fix #741 for future releases of Augeas

### CODE REVIEW

**Comment by kloczek** [comment]
Please add change `s/make dist/make distcheck/`

**Comment by hillu** [comment]
@kloczek Done.

**Comment by georgehansper** [comment]
I notice that  `.github/workflows/release.yml` contains the pattern `v*` for the purpose of matching tags.

I think this should be changed to `release-*` to bring it in line with established practice.

**Comment by hillu** [comment]
Sure.. Done.

**Review by georgehansper — APPROVED** [review]
Looks good to me

Anyone else have any comments or queries?

**Pull request merged**
