### PR TITLE
Allow parsing of options with equal sign

### PR DESCRIPTION
**Pull request by emildragu**
Options in sshd_config cand be speciffied using space, tab or equal sign.
They all have the same effect.

### CODE REVIEW

**Comment by emildragu** [comment]
I saw that CI failed and fixed by modified the commit, but probably CI did not trigger again: https://github.com/hercules-team/augeas/pull/587/commits/1717f0ef58e23610fd307ef221d675a2facf54ed . Shall I create a new commit fixing this?

**Comment by raphink** [comment]
@emildragu 	yes I saw the fix. However it only fixes one occurrence, there's 4 more problems to fix (listed in my previous comment).

**Comment by lutter** [comment]
It seems the typecheck errors have all been addressed now.

**Comment by raphink** [comment]
LGTM

**Pull request merged**
