### PR TITLE
Syslog: accept include directive

### PR DESCRIPTION
**Pull request by lutter**
Add syslog.conf from
https://svnweb.freebsd.org/base?view=revision&revision=308160 to test root,
too

Fixes https://github.com/hercules-team/augeas/issues/486

### CODE REVIEW

**Comment by lutter** [comment]
@rmdir could you have a look and verify that that's what you had in mind in #486 ?

**Comment by smortex** [comment]
Hello!

There is [interest in merging this into the FreeBSD port of augeas](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=232200) so that we ship this feature on FreeBSD.  However, we currently cannot use this PR patch because of conflicts with the `NEWS` file.

@lutter, would you mind refactoring a bit this pull request by splitting it in two commits:

* One including the actual fix (changes to `lenses/syslog.aug`, `lenses/tests/test_syslog.aug` and `tests/root/etc/syslog.conf`);
* One that updates the `NEWS` file.

We could then directly use the first commit patch in the port, ad you would be able to sync the `NEWS` file if desired without impact on the port we produce.

Thanks!

**Comment by raphink** [comment]
Merged as c608a4b6cd8b655325492ebc7dc2f3cc06de3252

**Comment by lutter** [comment]
@smortex is having this merged into master enough for you ? It'll show up in the next Augeas release anyway; if you want it earlier, you can just grab the updated lens and install that in the default lens path after Augeas' `make install`

**Comment by smortex** [comment]
@lutter sure, it's good for me! 

Thanks!

**Pull request closed without merging**
