### PR TITLE
GitHub Actions

### PR DESCRIPTION
**Pull request by raphink**

### CODE REVIEW

**Comment by raphink** [comment]
@hercules-team/maintainers Travis CI has become unusable. I'm looking to switch to GitHub Actions instead.

**Comment by raphink** [comment]
Hmmmm, the build fails on the "test-rwlock1" test https://github.com/raphink/augeas/runs/1792038926?check_suite_focus=true#step:8:341

**Comment by raphink** [comment]
I udpated gnulib but it's still failing the checks 🤷

**Review by georgehansper — COMMENTED** [review]
I ran this on my fork of Augeas, and it seems to work without any obvious errors.

I would suggest that a `make distcheck` step would be a good idea, as this is the `make` operation used to create release tarballs.

**Comment by georgehansper** [comment]
Merged from the command-line as commit 465f58a1, excluding the update to gnulib

**Pull request closed without merging**
