### PR TITLE
fix(lens): toml: write support

### PR DESCRIPTION
**Pull request by g0hl1n**
The toml lens fails to save simple toml files due to problems with multi
dimensional (>2) arrays.
Therefore disable arrays with more than 2 dimensions for now to enable
basic usage again.

This commit fixes issue #715 by applying the suggested workaround. If
anyone can come up with a better solution please feel free to do so.

Fixes: 5e1cd313 (TOML lens (#91), 2018-11-29)
Signed-off-by: Richard Leitner <richard.leitner@skidata.com>

### CODE REVIEW

**Comment by g0hl1n** [comment]
@raphink any questions or feedback on this PR?

**Comment by g0hl1n** [comment]
<PING>
Any feedback/questions?
@georgehansper @lutter @raphink

**Comment by georgehansper** [comment]
This solves the immediate problem, which is that the toml lens cannot save any files at all.
I'm happy to accept it as-is, and further improvements can be made at a later stage.

@raphink did you want to add/change anything ?

**Comment by g0hl1n** [comment]
@raphink any feedback from your side?

**Comment by g0hl1n** [comment]
[PING]
@raphink, @georgehansper any open merge-blocking issues with this PR?

**Review by georgehansper — APPROVED** [review]
This change resolves the immediate problem of not being able to _save_ toml files.

**Pull request merged**
