### PR TITLE
Add Ceph module

### PR DESCRIPTION
**Pull request by Paulche**
A simple bunch of tests is added as well.

### CODE REVIEW

**Comment by raphink** [comment]
That looks good. Could you just add NaturalDocs documentation to the lens please? (see `keepalived.aug` for example).

**Comment by Paulche** [comment]
Good point! I'll add the documentation soon. Thanks!

**Comment by pspacek** [comment]
@Paulche Could you add the documented lens to this PR? Thanks!

**Comment by lutter** [comment]
@raphink any objections to merging this as-is ? I'd rather have this in without docs if it works

**Comment by lutter** [comment]
Merged as 1a3b4889

**Pull request closed without merging**
