### PR TITLE
lenses: Allow whitespace at the end of kernel commnd line

### PR DESCRIPTION
**Pull request by rwmjones**
Reported-by: Yongkui Guo
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2159282
Signed-off-by: Richard W.M. Jones <rjones@redhat.com>

### CODE REVIEW

**Review by igalic — COMMENTED** [review]
do we not have tests for this?

**Comment by rwmjones** [comment]
I'm not sure if you're asking if we test the feature in general (yes), or if we tested before whitespace at the end of a command line (no), or if I added a new test for this (also no) ?

**Comment by igalic** [comment]
if we already have tests for the feature, then we should extend the tests, too

(i'm not going to ask people to add tests where there are none to begin with)

**Comment by rwmjones** [comment]
The updated commit adds a test for a command line ending in whitespace.  Hope I did it right!

**Review by georgehansper — APPROVED** [review]
Works as described, includes a specific test

**Pull request merged**
