### PR TITLE
Updated for multipath-0.4.9-99.el7.

### PR DESCRIPTION
**Pull request by XMol**

### CODE REVIEW

**Comment by domcleal** [comment]
You can reproduce the test failures locally either with `make check`, or by just running `augparse -I lenses lenses/tests/test_multipath.aug`. It's failing to parse something in the defaults group at around line 31 I would guess.

(You can also add new examples to this test file to cover any new functionality you've added.)

**Comment by XMol** [comment]
Hi Dominic,

there is no test_multipath.aug lens - does that explain the failed check?

Ciao,
Xavier.

**Comment by domcleal** [comment]
It's here, in the git tree: https://github.com/XMol/augeas/blob/b8af6f930b05a459bc4c353fc59fbfe28c6534c3/lenses/tests/test_multipath.aug

**Comment by XMol** [comment]
Yes, I just found it, too. Was looking into the wrong tests directory...

**Comment by XMol** [comment]
Ok, added some more undocumented attributes, that were included in the test lens.

Of course, whatever isn't mentioned in the man pages, but was implemented by the vendors for their individual products, is difficult to test in advance...

**Comment by domcleal** [comment]
Merged, thanks for the patch @XMol.

**Pull request merged**
