### PR TITLE
ClamAv, MailScanner, Pgbouncer, PylonsPaste lenses

### PR DESCRIPTION
**Pull request by akissa**
Added lenses to parse ClamAV, MailScanner, Pgbouncer, Pylons Paste configuration files.

### CODE REVIEW

**Comment by raphink** [comment]
These look good. Can you rebase and squash the commits please?

**Comment by akissa** [comment]
Done the rebase and squash

**Comment by raphink** [comment]
The current branch conflicts with master. Can you rebase and squash into one commit per added lens please (4 commits in total)?

**Comment by akissa** [comment]
I do not see how i can do that, aa1b9f1 contains tests for all 4 lenses.

**Comment by raphink** [comment]
Nevermind, I'll do it then.

**Comment by raphink** [comment]
FYI https://github.com/hercules-team/augeas/pull/200 is what I meant

**Comment by raphink** [comment]
Merged as 3e20740..ab6d8b2

**Pull request closed without merging**
