### PR TITLE
Add additional unit tests for yum lense

### PR DESCRIPTION
**Pull request by jcpunk**
When writing a new lense using logic from this lense I uncovered unexpected behaviour with whitespace.

The tests added here expose this oddity.

### CODE REVIEW

**Comment by raphink** [comment]
Thanks. I usually add a `needs-tests` label to PRs without tests, but this one has tests and no code...

**Comment by jcpunk** [comment]
My primary worry is that I'm doing the testing wrong.... if I'm not, this is a real bug that I'm not sure how to fix.

**Comment by jcpunk** [comment]
After a night's sleep, I realized what was wrong with my tests.  In theory I'm now running the tests right and should have more coverage than before.

**Comment by jcpunk** [comment]
rebased off master

**Comment by jcpunk** [comment]
rebased off master

**Comment by georgehansper** [comment]
This change does not fail any tests - were you expecting it to fail on the yum lens ?

**Comment by jcpunk** [comment]
Nope i was just adding some coverage to the yum lense and providing a
syntax cheat sheet for when i do this sort of thing.

**Pull request merged**
