### PR TITLE
Fixes #194 - Allow multiple interfaces in redis bind command

### LINKED ISSUE #194: Redis lense doesn't support multiple IPs in bind command

### PR DESCRIPTION
**Pull request by yannh**
I added the tests from mfournier, and tried to fix the tests following the help from lutter... It is important to keep in mind that you would now set bind interfaces with /files/etc/redis.conf/bind/1 instead of /files/etc/redis.conf/bind which some people might be using happily with just one interface, so this might break for some people. 

Also, I admit I'm not too sure of the difference between /files/etc/redis.conf/bind/1 and /files/etc/redis.conf/bind[1] - I failed at getting the latter version to work.

### CODE REVIEW

**Comment by mfournier** [comment]
:sparkles: :+1:

**Comment by raphink** [comment]
I think I would rather use multiple `bind` nodes (resulting in  `bind[1]` instead of `bind/1`) in order to avoid breaking compatibility.

However, that might be harder to implement, as it will probably introduce an ambiguity if two `bind` nodes follow each other.

**Comment by raphink** [comment]
@yannh ping?

**Comment by yannh** [comment]
@raphink pong, sorry, long holidays and job switch :) Can I help?

**Comment by raphink** [comment]
@yannh did you see my comments?

**Comment by lutter** [comment]
Closing this in favor of PR #580.

**Pull request closed without merging**
