### PR TITLE
Update sshd lens for additional list

### PR DESCRIPTION
**Pull request by dave-re-imprivata**
Resolves issue #804

### CODE REVIEW

**Review by igalic — COMMENTED** [review]
👍

**Comment by dave-re-imprivata** [comment]
@igalic - I'm sure I've just missed some step along the way, here - any idea how I request review here, so I can move this PR along?

**Comment by igalic** [comment]
cc @georgehansper

**Review by georgehansper — APPROVED** [review]
Thanks for including the test

**Pull request merged**
