### PR TITLE
Keepalived updates

### PR DESCRIPTION
**Pull request by jtopjian**
I didn't review any of the virtual server stuff since I'm not working with it at the moment.

As always, please let me know if there are better ways of achieving any of this. :smile:

### CODE REVIEW

**Comment by raphink** [comment]
This looks good (although I'm afraid it's going to make this lens —probably already the heaviest one— even heavier). Can you just squash some commits please?

**Comment by jtopjian** [comment]
I've noticed that this lens is a bit slow -- is that what you mean by "heavy"?

Sure can. The multiple commits were to just make a code review easier. 

Is it OK if I just squash everything into 1 commit with a summary? That'll probably be the cleanest with all of the spacing fixes.

**Comment by raphink** [comment]
I would rather you squash the "more of that" commits into the "that" original ones, e.g. "More spacing/tabs" into "Tabs and spacing fixes".

Also, I'd appreciate if you could prepend "Keepalived: " in front of each commit message.

**Comment by jtopjian** [comment]
OK! Thank you for the suggestions. This PR looks much cleaner now :)

**Comment by raphink** [comment]
Merged. Thank you.

**Pull request closed without merging**
