### PR TITLE
Support for ifupdown2 stanza and bug fixes for dhcpd.conf quotations

### PR DESCRIPTION
**Pull request by rcgoodfellow**
Hi,

This pull request updates two files

**interfaces.aug**
- make the family and method stanza parameters optional to support this aspect of ifupdown2

**dhcpd.aug**
Enforce double quotation for the following host configuration elements
- `ddns-hostname`
- `ddns-domainname`
- `option host-name`
- `option domain-name`

These changes are motivated by the following:

This causes an error in dhcpd

```
host murphy {
  option domain-name murphy.example.org;
}
```

```
$ dhcpd -d
Internet Systems Consortium DHCP Server 4.3.5b1
[snip]
/etc/dhcp/dhcpd.conf line 116: semicolon expected.
  option domain-name murphy.
                           ^
Configuration file errors encountered -- exiting
```

whereas this is ok

```
host murphy {
  option domain-name "murphy.example.org";
}
```

There is also a fix to allow bare host names, I was getting the following from the lens as is

```
host "murphy" {
  option domain-name "murphy.example.org";
}
```

which seemingly should have the host name without the quotes

```
host murphy {
  option domain-name "murphy.example.org";
}
```

### CODE REVIEW

**Comment by lutter** [comment]
Hi Ryan,

thanks for your contribution ! Unfortunately, the typechecker complains about both lenses (simply run `augparse lenses/dhcpd.aug` or some such) and there are no unit tests (they should go into `lenses/tests/test_dhcpd.aug`)

I've looked at fixing the typecheck errors; for `interfaces.aug` it seems the following change works:
```diff
--- a/lenses/interfaces.aug
+++ b/lenses/interfaces.aug
@@ -38,7 +38,7 @@ let stanza_param (l:string) = [ sep_spc . label l . sto_to_spc ]
 
 (* Define reseverved words and multi-value options*)
 let stanza_word =
-   /(source(-directory)?|iface|auto|allow-[a-z-]+|mapping|bond-slaves|bridge-ports)/
+   /(source(-directory)?|iface|auto|allow-[a-z-]+|mapping|bond-slaves|bridge-ports)|family|method/
 
 (* Define stanza option indentation *)
 let stanza_indent = del /[ \t]*/ "   "
@@ -84,8 +84,8 @@ let multi_option (t:string) = [ stanza_indent . array t t . eol ]
 
 let iface   = [ Util.indent
               . stanza_id    "iface"
-              . ( stanza_param "family" )?
-              . ( stanza_param "method" )?
+              . (( stanza_param "family" )?
+                 . ( stanza_param "method" ))?
               . eol
               . ( stanza_option
                 | multi_option "bond-slaves"
```

For `dhcpd.aug` I haven't figured out the fix, partly because I am not entirely sure what should be changed: should the argument to the four options you list above always be forced to be quoted ? Do we need to worry about values that do not have a `.` in them and are bare ?

It would really help to have tests for these things to help clarify what is intended. You might also want to split the PR into two, so that we can merge them independently once you have tests.

**Comment by rcgoodfellow** [comment]
@lutter ok that sounds good. I will look at the testing format and figure out how to write a test that isolates these issues, gets things passing and get back to you. cheers

**Comment by raphink** [comment]
@rcgoodfellow 	are you still interested in getting this merged?

**Comment by lutter** [comment]
I am closing this for now because there hasn't been any activity in quite some time. Feel free to reopen if there is an update.

**Pull request closed without merging**
